import {
  ShieldCheck,
  AlertTriangle,
  ShieldAlert,
  Clock,
  Activity,
} from "lucide-react";
import "./ResultsDashboard.css";

export function ResultsDashboard({ result, onReset }) {
  const { classification, flagged_ranges, heuristic_score, diagnostics } =
    result;

  const getClassContent = () => {
    switch (classification.class_id) {
      case 0:
        return {
          icon: <ShieldCheck size={64} className="status-icon real" />,
          title: "Authentic Video",
          colorClass: "real",
          desc: "No AI manipulation or temporal artifacts detected.",
        };
      case 1:
        return {
          icon: <AlertTriangle size={64} className="status-icon ai" />,
          title: "Partial AI Manipulation",
          colorClass: "ai",
          desc: "Detected localized face-swaps or specific injected AI segments.",
        };
      case 4:
        return {
          icon: <ShieldAlert size={64} className="status-icon full-ai" />,
          title: "Fully AI Generated",
          colorClass: "full-ai",
          desc: "High probability this entire video was generated by an AI model (e.g. Sora, Runway, Pika).",
        };
      default:
        return {
          icon: <AlertTriangle size={64} className="status-icon" />,
          title: "Unknown Result",
          colorClass: "",
          desc: "The classifier returned an unrecognized state.",
        };
    }
  };

  const content = getClassContent();

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  return (
    <div className="dashboard-container">
      <div className={`panel verdict-panel ${content.colorClass}`}>
        <div className="verdict-header">
          {content.icon}
          <div className="verdict-text">
            <h2>{content.title}</h2>
            <p>{content.desc}</p>
          </div>
        </div>

        <div className="metrics-grid">
          <div className="metric-box">
            <span className="metric-label">Heuristic Variance</span>
            <span className="metric-value">
              {(heuristic_score * 100).toFixed(1)}%
            </span>
          </div>
          <div className="metric-box">
            <span className="metric-label">Flagged Coverage</span>
            <span className="metric-value">
              {(diagnostics.coverage * 100).toFixed(1)}%
            </span>
          </div>
          <div className="metric-box">
            <span className="metric-label">Windows Processed</span>
            <span className="metric-value">
              {diagnostics.total_windows_processed}
            </span>
          </div>
        </div>
      </div>

      {classification.class_id === 1 &&
        flagged_ranges &&
        flagged_ranges.length > 0 && (
          <div className="panel timestamps-panel">
            <div className="panel-header">
              <Clock size={20} className="header-icon text-ai" />
              <h3>Detected Manipulation Timestamps</h3>
            </div>

            <ul className="timestamp-list">
              {flagged_ranges.map((range, idx) => (
                <li key={idx} className="timestamp-item">
                  <div className="time-range">
                    <span className="time-pill">{formatTime(range.start)}</span>
                    <span className="time-sep">to</span>
                    <span className="time-pill">{formatTime(range.end)}</span>
                  </div>
                  <div className="confidence-score">
                    <Activity size={16} />
                    <span>
                      Peak Confidence:{" "}
                      {(range.peak_score || range.score).toFixed(2)}
                    </span>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        )}

      <button className="button-primary reset-btn" onClick={onReset}>
        Analyze Another Video
      </button>
    </div>
  );
}
