import time
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
import pandas as pd
from tqdm import tqdm
from dataset.dataloader import DeepfakeWindowDataset, collate_fn
from torch.utils.data import DataLoader
import timm

def main():
    print("Beginning DataLoader Benchmarks...")
    csv_path = 'dataset/labels/windows_index_test.csv' # Assume generated by test
    
    # Check if CSV exists, if not we will skip real tests and instruct user.
    try:
        df = pd.read_csv(csv_path)
    except FileNotFoundError:
        print(f"File {csv_path} not found. Please run the dummy generation test first (test_stage3.py).")
        return

    # Initialize Dataset
    dataset = DeepfakeWindowDataset(csv_file=csv_path, augment=True, seq_len=20, fps=5, target_size=224)
    dl = DataLoader(dataset, batch_size=4, shuffle=True, collate_fn=collate_fn, num_workers=0)
    
    print(f"\n--- Performance Check (__getitem__) ---")
    start_time = time.time()
    num_samples = min(100, len(dataset))
    
    successful_fetches = 0
    for i in tqdm(range(num_samples)):
         try:
             _ = dataset[i]
             successful_fetches += 1
         except Exception as e:
             print(f"Error on sample {i}: {e}")
             
    end_time = time.time()
    avg_time_ms = ((end_time - start_time) / successful_fetches) * 1000 if successful_fetches > 0 else float('inf')
    
    print(f"Successfully processed: {successful_fetches} windows")
    print(f"Average time per __getitem__ (decord + crop + transform): {avg_time_ms:.2f} ms")
    
    if avg_time_ms <= 200:
        print("✓ Performance PASS: Under 200ms threshold.")
    else:
        print("X Performance FAIL: Exceeds 200ms limit! Investigate decord bottleneck.")

    print(f"\n--- OOM & Integrity Check (VRAM: batch_size=4, Grad Accum=8, FP16) ---")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Running on {device}")
    
    try:
        model = timm.create_model('efficientnet_b4', pretrained=False, num_classes=1).to(device)
        scaler = torch.amp.GradScaler('cuda') if device.type == 'cuda' else None
        
        # Grab one batch
        batch_tensors, batch_labels, _ = next(iter(dl))
        batch_tensors = batch_tensors.to(device) # [4, 20, 3, 224, 224]
        batch_labels = batch_labels.to(device).unsqueeze(1) # [4, 1]
        
        B, T, C, H, W = batch_tensors.shape
        # Flatten to [80, 3, 224, 224] for backbone
        x = batch_tensors.view(B*T, C, H, W)
        
        with torch.amp.autocast('cuda') if device.type == 'cuda' else torch.autocast('cpu'):
            print("Forward Pass Started...")
            logits = model(x) # [80, 1]
            # Time pool to [4, 1] via mean across time dimension
            logits_reshaped = logits.view(B, T, -1).mean(dim=1)
            loss = torch.nn.functional.binary_cross_entropy_with_logits(logits_reshaped, batch_labels) / 8 # simulate gradient accumulation 8
            
        print("Backward Pass Started...")
        if scaler:
            scaler.scale(loss).backward()
        else:
            loss.backward()
            
        print("✓ Memory & Integrity PASS: No OOM detected during [4, 20, 3, 224, 224] fp16 pass.")
        print("✓ Tensor Integrity Verified.")
        
    except torch.cuda.OutOfMemoryError as e:
        print("X Memory FAIL: Caught OutOfMemoryError!")
        torch.cuda.empty_cache()
    except Exception as e:
        print(f"X Unexpected Error: {e}")

if __name__ == "__main__":
    main()
